### ISSUE TITLE
RollbackCore Error with Skript - Depends on older version of Skript

### ISSUE THREAD

**Issue by fools12** [null321-jared/rollbackcore-legacy#1]
Whenever I have RollbackCore and the Skript plugin together, RollbackCore errors out and will not load.

Server Version: Paper 1.12.2
RollbackCore version: 2.5.0
Skript version: 2.6.4

Console Error:
[Server thread/ERROR]: Error occurred while enabling RollbackCore v2.5.0 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1223) ~[?:?]
	at ch.njol.skript.Skript.registerEvent(Skript.java:1411) ~[?:?]
	at net.shadowxcraft.rollbackcore.SkriptSupport.initSkriptSupport(SkriptSupport.java:18) ~[?:?]
	at net.shadowxcraft.rollbackcore.Main.onEnable(Main.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:833) [?:?] 

Full server log: https://pastebin.com/gvRg9GyU

Any help would be greatly appreciated. RollbackCore is the only (good) area rollback plugin I could find that does exactly what I need, and I use the Skript plugin to automate it. Thank you!

**Comment by fools12** [comment]
Issue resolved

**Comment by null321-jared** [comment]
I'm glad you resolved the issue! What was the problem, in case someone else experiences it? Was it loaded out of order with a plugin manager?

**Comment by fools12** [comment]
I was originally using the latest Skript version 2.6.4; I downgraded to 2.4 and that resolved the issue.

**Comment by null321-jared** [comment]
Thanks for the info! Would you like me to send you an updated version for the latest skript when I get around to updating it?
This issue is still valid, because RollbackCore depends on an old version of Skript.

**Comment by fools12** [comment]
https://github.com/SkriptLang/Skript/releases/download/2.6.4/Skript-2.6.4.jar
